# Generated by Django 3.2 on 2021-12-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
