# Generated by Django 3.2 on 2021-10-06 11:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_on_list',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
