# Generated by Django 3.2 on 2021-10-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_autoblogging'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoblogging',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
