# Generated by Django 3.2 on 2022-01-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_post_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(max_length=255, upload_to='billboard')),
            ],
        ),
    ]
