# Generated by Django 3.2 on 2022-01-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_billboard_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
