# Generated by Django 3.2 on 2022-03-26 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('news', '0025_auto_20220211_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='image2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='billboard'),
        ),
    ]
