# Generated by Django 3.2 on 2022-05-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20220506_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
