# Generated by Django 3.2 on 2022-05-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20220507_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='display_news',
            new_name='display_list',
        ),
    ]
