# Generated by Django 3.2 on 2022-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vineyards', '0061_auto_20220508_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeoRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ManyToManyField(blank=True, to='filters.Country')),
            ],
        ),
        migrations.CreateModel(
            name='WorldArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geo_region', models.ManyToManyField(blank=True, to='filters.GeoRegion')),
            ],
        ),
        migrations.CreateModel(
            name='WineRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vineyards', models.ManyToManyField(blank=True, to='vineyards.Vineyard')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='wine_rg',
            field=models.ManyToManyField(blank=True, to='filters.WineRegion'),
        ),
    ]
