# Generated by Django 3.2 on 2022-06-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_auto_20220525_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoRegion',
            new_name='WorldRegion',
        ),
        migrations.DeleteModel(
            name='WorldArea',
        ),
    ]
