# Generated by Django 3.2 on 2022-06-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0004_auto_20220601_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worldregion',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
