# Generated by Django 3.2 on 2022-06-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0005_auto_20220602_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='worldregion',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
