# Generated by Django 3.2 on 2021-09-21 04:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vineyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField()),
                ('rating', models.FloatField()),
                ('google_map', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('grapes', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('visits', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vineyards.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vineyards.region')),
            ],
        ),
    ]
