# Generated by Django 3.2 on 2021-09-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='cover',
            field=models.ImageField(default='', upload_to='vineyard/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_images', models.ImageField(upload_to='region-image/')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vineyards.region')),
            ],
        ),
    ]
