# Generated by Django 3.2 on 2021-09-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0003_auto_20210925_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='regionchild',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='vineyard',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
