# Generated by Django 3.2 on 2021-09-27 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0005_auto_20210925_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='ad_manager',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='region',
            name='sidebar',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='vineyard',
            name='ad_manager',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='vineyard',
            name='sidebar',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
