# Generated by Django 3.2 on 2021-09-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0007_auto_20210928_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='ad_manager',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='ad_manager',
            field=models.TextField(blank=True),
        ),
    ]
