# Generated by Django 3.2 on 2021-09-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0008_auto_20210928_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='display_on_navbar',
            field=models.BooleanField(default=True),
        ),
    ]
