# Generated by Django 3.2 on 2021-09-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0009_region_display_on_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='logo_on_navbar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
