# Generated by Django 3.2 on 2021-09-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0010_region_logo_on_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='cover_slider',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vineyard',
            name='top_slider',
            field=models.BooleanField(default=True),
        ),
    ]
