# Generated by Django 3.2 on 2021-09-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0011_auto_20210929_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='YardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yard-image/')),
                ('vineyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vineyards.vineyard')),
            ],
        ),
        migrations.CreateModel(
            name='YardCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yard-cover-image/')),
                ('vineyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vineyards.vineyard')),
            ],
        ),
    ]
