# Generated by Django 3.2 on 2021-09-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0013_vineyard_region_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='under_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='cover_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='top_slider',
            field=models.BooleanField(default=False),
        ),
    ]
