# Generated by Django 3.2 on 2021-10-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0014_auto_20210930_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vineyard',
            name='region_child',
        ),
        migrations.DeleteModel(
            name='RegionChild',
        ),
    ]
