# Generated by Django 3.2 on 2021-10-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0016_auto_20211001_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_parent',
            field=models.ManyToManyField(blank=True, related_name='_vineyards_region_region_parent_+', to='vineyards.Region'),
        ),
    ]
