# Generated by Django 3.2 on 2021-10-01 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0017_region_region_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region_parent',
        ),
        migrations.AddField(
            model_name='region',
            name='region_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vineyards.region'),
        ),
    ]
