# Generated by Django 3.2 on 2021-10-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0018_auto_20211001_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='regions', to='vineyards.Region'),
        ),
    ]
