# Generated by Django 3.2 on 2021-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0019_vineyard_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversliderimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='yard-cover-image/'),
        ),
        migrations.AlterField(
            model_name='region',
            name='logo_on_navbar',
            field=models.ImageField(blank=True, max_length=255, upload_to='logo-on-navbar/'),
        ),
        migrations.AlterField(
            model_name='regionimage',
            name='region_images',
            field=models.ImageField(max_length=255, upload_to='region-image/'),
        ),
        migrations.AlterField(
            model_name='topsliderimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='yard-image/'),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='cover',
            field=models.ImageField(max_length=255, upload_to='vineyard/'),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='custom_overlay',
            field=models.ImageField(blank=True, max_length=255, upload_to='custom-rating/'),
        ),
    ]
