# Generated by Django 3.2 on 2021-10-21 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0022_region_description_on_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.IntegerField(default=50, validators=[
                 django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('review', models.TextField()),
                ('value', models.IntegerField(default=50, validators=[
                 django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('service', models.IntegerField(default=50, validators=[
                 django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('cleanliness', models.IntegerField(default=50, validators=[
                 django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('location', models.IntegerField(default=50, validators=[
                 django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sustainability', models.IntegerField(default=50, validators=[
                 django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
