# Generated by Django 3.2 on 2021-10-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0023_reviewandrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrating',
            name='vineyard',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='vineyards.vineyard'),
            preserve_default=False,
        ),
    ]
