# Generated by Django 3.2 on 2021-11-01 01:56

from django.db import migrations, models
import django.utils.timezone
import vineyards.models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0027_alter_reviewandrating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrating',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewandrating',
            name='review',
            field=models.TextField(validators=[vineyards.models.review_validator]),
        ),
    ]
