# Generated by Django 3.2 on 2021-11-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0028_auto_20211101_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrating',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
