# Generated by Django 3.2 on 2021-12-13 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0031_auto_20211207_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VineyardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('vineyard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vineyards.vineyard')),
            ],
        ),
    ]
