# Generated by Django 3.2 on 2021-12-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0032_auto_20211213_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyarduser',
            name='website',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
