# Generated by Django 3.2 on 2021-12-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0033_vineyarduser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='visits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vineyarduser',
            name='address',
            field=models.TextField(),
        ),
    ]
