# Generated by Django 3.2 on 2021-12-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0034_auto_20211216_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='google_map',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
