# Generated by Django 3.2 on 2021-12-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0036_vineyard_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyarduser',
            name='web_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
