# Generated by Django 3.2 on 2022-01-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0037_vineyarduser_web_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='display_billboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='display_news',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vineyard',
            name='display_billboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vineyard',
            name='display_news',
            field=models.BooleanField(default=True),
        ),
    ]
