# Generated by Django 3.2 on 2022-02-09 05:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0038_auto_20220108_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='description_on_list',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='sidebar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='sidebar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
