# Generated by Django 3.2 on 2022-03-08 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vineyards.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vineyards', '0040_auto_20220211_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(validators=[vineyards.models.review_validator])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('rr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vineyards.reviewandrating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
