# Generated by Django 3.2 on 2022-03-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20220211_1208'),
        ('vineyards', '0043_alter_comment_rr'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='news',
            field=models.ManyToManyField(blank=True, to='news.Category'),
        ),
        migrations.AddField(
            model_name='vineyard',
            name='listing_title1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vineyard',
            name='news',
            field=models.ManyToManyField(blank=True, to='news.Category'),
        ),
    ]
