# Generated by Django 3.2 on 2022-03-17 04:22

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vineyards', '0044_auto_20220312_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='cover2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
