# Generated by Django 3.2 on 2022-03-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0045_vineyard_cover2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, upload_to='vineyard/'),
        ),
    ]
