# Generated by Django 3.2 on 2022-03-23 08:03

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vineyards', '0046_alter_vineyard_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='logo_on_navbar2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_on_navbar2', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='thumbnail2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail2', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
