# Generated by Django 3.2 on 2022-03-25 03:39

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vineyards', '0048_vineyard_custom_overlay2'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionimage',
            name='region_images2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
