# Generated by Django 3.2 on 2022-03-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0050_auto_20220325_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversliderimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='yard-cover-image/'),
        ),
        migrations.AlterField(
            model_name='regionimage',
            name='region_images',
            field=models.ImageField(blank=True, max_length=255, upload_to='region-image/'),
        ),
        migrations.AlterField(
            model_name='topsliderimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='yard-image/'),
        ),
    ]
