# Generated by Django 3.2 on 2022-04-06 05:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0051_auto_20220328_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='google_map',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='grapes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vineyards.region'),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='visits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='wine_rg',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vineyard',
            name='wines',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vineyarduser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vineyarduser',
            name='email1',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vineyarduser',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vineyarduser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vineyarduser',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vineyarduser',
            name='web_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vineyarduser',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
