# Generated by Django 3.2 on 2022-04-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0053_auto_20220412_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VineyardUser',
        ),
    ]
