# Generated by Django 3.2 on 2022-04-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0054_delete_vineyarduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
