# Generated by Django 3.2 on 2022-04-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0055_vineyard_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, upload_to='img/%Y/%m/'),
        ),
    ]
