# Generated by Django 3.2 on 2022-04-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0056_alter_vineyard_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyard',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
