# Generated by Django 3.2 on 2022-05-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0059_auto_20220429_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='display_news',
            new_name='display_list',
        ),
        migrations.RenameField(
            model_name='vineyard',
            old_name='display_news',
            new_name='display_list',
        ),
    ]
