# Generated by Django 3.2 on 2022-05-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0060_auto_20220508_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='listing_title2',
            new_name='carousel_title',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='news',
            new_name='list_carousel',
        ),
        migrations.RenameField(
            model_name='vineyard',
            old_name='listing_title1',
            new_name='carousel_title',
        ),
        migrations.RenameField(
            model_name='vineyard',
            old_name='news',
            new_name='list_carousel',
        ),
    ]
