# Generated by Django 3.2 on 2022-05-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0061_auto_20220508_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='vineyard',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
