# Generated by Django 3.2 on 2021-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(max_length=200, upload_to='news/'),
        ),
    ]
