# Generated by Django 3.2 on 2021-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_alter_post_ad_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(max_length=255, upload_to='news/'),
        ),
    ]
