# Generated by Django 3.2 on 2021-10-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
