# Generated by Django 3.2 on 2021-10-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_autoblogging_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='list.Tag'),
        ),
    ]
