# Generated by Django 3.2 on 2021-10-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_alter_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_on_list',
        ),
    ]
