# Generated by Django 3.2 on 2021-12-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_remove_post_body_on_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
    ]
