# Generated by Django 3.2 on 2022-01-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_billboard_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_billboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='display_news',
            field=models.BooleanField(default=True),
        ),
    ]
