# Generated by Django 3.2 on 2022-05-09 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0029_rename_display_news_post_display_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='list_carousel',
            field=models.ManyToManyField(blank=True, related_name='_list_post_list_carousel_+', to='list.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category+', to='list.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, upload_to='news'),
        ),
    ]
