# Generated by Django 3.2 on 2022-05-10 12:54

from django.db import migrations, models
import django.db.models.deletion
import list.models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0030_auto_20220509_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=list.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='category+', to='list.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
