# Generated by Django 3.2 on 2022-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0031_auto_20220510_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_cover',
            field=models.BooleanField(default=True),
        ),
    ]
