# Generated by Django 3.2 on 2021-09-20 15:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('PAGE', 'Page'), ('HOME_PAGE', 'Home Page'), ('HOME_PAGE_SIDEBAR', 'Home Page Sidebar')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
