# Generated by Django 3.2 on 2021-09-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0002_contentpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
