# Generated by Django 3.2 on 2021-09-27 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0003_alter_contentpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='ad_manager',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='sidebar',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
