# Generated by Django 3.2 on 2021-09-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0006_alter_contentpage_ad_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages_app.contentpage')),
            ],
        ),
    ]
