# Generated by Django 3.2 on 2021-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0007_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(max_length=255, upload_to='page/'),
        ),
    ]
