# Generated by Django 3.2 on 2021-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0020_auto_20211001_2217'),
        ('pages_app', '0011_auto_20211002_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='category',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='category',
            field=models.ManyToManyField(blank=True, to='vineyards.Region'),
        ),
    ]
