# Generated by Django 3.2 on 2021-10-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0020_auto_20211001_2217'),
        ('pages_app', '0012_auto_20211002_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='category',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vineyards.region'),
        ),
    ]
