# Generated by Django 3.2 on 2021-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0013_auto_20211002_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('types', models.CharField(choices=[('DEFAULT', 'Default'), ('REGION', 'Region'), ('DISCOVER', 'Discover')], max_length=20)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
    ]
