# Generated by Django 3.2 on 2021-10-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0015_auto_20211003_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='types',
            field=models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page')], max_length=20),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
