# Generated by Django 3.2 on 2021-10-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0016_auto_20211003_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='types',
            field=models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page'), ('SEARCH_PAGE', 'Search Page')], max_length=20),
        ),
    ]
