# Generated by Django 3.2 on 2021-10-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0017_alter_contentpage_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='types',
            field=models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page'), ('SEARCH_PAGE', 'Search Page'), ('GLOBAL_TRAVEL_NEWS', 'Global Travel News')], max_length=20),
        ),
    ]
