# Generated by Django 3.2 on 2021-10-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0020_contentpage_content_on_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='types',
            field=models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page'), ('SEARCH_PAGE', 'Search Page'), ('CATEGORY', 'Category')], max_length=20),
        ),
    ]
