# Generated by Django 3.2 on 2021-12-07 06:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0022_contentpage_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar', ckeditor.fields.RichTextField(blank=True)),
                ('ad_manager', models.TextField(blank=True)),
            ],
        ),
    ]
