# Generated by Django 3.2 on 2022-01-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0023_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='display_billboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='display_news',
            field=models.BooleanField(default=True),
        ),
    ]
