# Generated by Django 3.2 on 2022-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineyards', '0038_auto_20220108_2144'),
        ('pages_app', '0024_auto_20220108_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='category',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='category',
            field=models.ManyToManyField(blank=True, to='vineyards.Region'),
        ),
    ]
