# Generated by Django 3.2 on 2022-01-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0025_auto_20220109_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
