# Generated by Django 3.2 on 2022-02-11 05:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0026_alter_contentpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='additional_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content_on_list',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='sidebar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='sidebar',
            field=models.TextField(blank=True),
        ),
    ]
