# Generated by Django 3.2 on 2022-02-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0027_auto_20220211_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
    ]
