# Generated by Django 3.2 on 2022-02-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20220211_1208'),
        ('pages_app', '0029_footer_new_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='news',
            field=models.ManyToManyField(blank=True, to='news.Category'),
        ),
    ]
