# Generated by Django 3.2 on 2022-03-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0031_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='listing_title1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='listing_title2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='listing_title3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
