# Generated by Django 3.2 on 2022-03-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0033_auto_20220326_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='page/'),
        ),
    ]
