# Generated by Django 3.2 on 2022-04-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0034_alter_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
