# Generated by Django 3.2 on 2022-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0035_alter_contentpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='types',
            field=models.CharField(choices=[('PAGE', 'Page'), ('FOOTER', 'Footer'), ('HOME_PAGE', 'Home Page'), ('SEARCH_PAGE', 'Search Page'), ('CATEGORY', 'Category'), ('WITHOUT_SIDEBAR', 'Without Sidebar')], max_length=20),
        ),
    ]
