# Generated by Django 3.2 on 2022-05-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0039_alter_contentpage_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='listing_title3',
            new_name='carousel_title',
        ),
    ]
