# Generated by Django 3.2 on 2022-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0040_rename_listing_title3_contentpage_carousel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='listing_title3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
