# Generated by Django 3.2 on 2022-05-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0041_contentpage_listing_title3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='display_news',
            new_name='display_list',
        ),
    ]
