# Generated by Django 3.2 on 2022-05-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0042_rename_display_news_contentpage_display_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpage',
            old_name='show_listing',
            new_name='show_listing1',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='show_listing2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='show_listing3',
            field=models.BooleanField(default=False),
        ),
    ]
